### PR TITLE
V1.0

### PR DESCRIPTION
**Pull request by Rav4s**
# Quality Assurance Checklist
To make reviews more efficient, please make sure the board meets the following standards and check everything off once the board meets the quality check. Once everything has been checked, the assigned reviewers will begin the review process. _Edit this description to check off the list._

There are exceptions with all guidelines. As long as your decisions are justified, then you are good! Contact the reviewers or the leads about any exceptions.

**Please *read* every word on *every* bullet point before checking off the corresponding box.**

## Minimum Prerequisites
- [X] The board passes ERC and DRC.
    - Note some ERC warnings are acceptable (**_CAUTION_** please be careful)
    - Note some DRC warnings are acceptable (less so than ERC: **_CAUTION_** please be careful).
- [X] All traces are routed.
- [X] Units are in metric.
- [ ] Gerbers are in a zip file in the main directory (after physical design is done)

**Please *read* every word on *every* bullet point before checking off the corresponding box.**

## Schematic Level Requirements 
- [X] Is proper noise resistance given to all peripheral devices (bypass caps and coils/ferrites)?  
- [X] Is proper ESD protection given to all MCU input pins (zener diodes)? You could also write the input pin rating for the MCU on the schematic.  
- [X] Is proper power protection given to peripheral devices (zener diodes)?  
- [X] Are peripheral units used properly (reading datasheet)?  
- [X] Are testing points added at useful places?  
- [X] Is there proper short to GND protection at MCU outputs (inline resistors)?  
- [X] Do ADC inputs have caps (appropriately sized to prevent RC delay)?  
- [X] Are ADC inputs biased so there is room above expected value to determine if value is being overflowed?  
- [X] Are LEDs located at useful places (comm, power, debugging, extra GPIO)? They should be placed in locations   
- [X] Are parts chosen easy to collect?  
- [X] Are parts chosen easy to solder?  
- [X] Is there reverse polarity protection on inputs?  
- [X] Do parts in the schematic match the actual part datasheet?

**Please *read* every word on *every* bullet point before checking off the corresponding box.**

## BOM Requirements
- [x] **Bill Of Materials**: is there an Excel Sheet BOM and a Mouser Cart link?
- [x] Are *all* the correct parts in the BOM?
- [x] Is each part in the Mouser Cart in stock (or do we have the part in stock)?
- [x] Does each part in the Mouser Cart have a margin for part quantity?
- [x] Does every component in the schematic have a footprint, mouser link/datasheet, and reference number associated with it?

**Please *read* every word on *every* bullet point before checking off the corresponding box.**

### 2D Spacing
- [X] The components are spaced out at an optimal distance.
    - All components can be easily hand-soldered.
    - IPC-SM-782A Standard requires a minimum distance of 1.0mm from edge to edge.
- [X] Components that are in parallel with each other are spaced out at an equal distance when possible.
- [X] The components are aligned with each other when possible.
- [x] Components are grouped based off of functionality.
    - E.g. all components for CAN should be grouped.
- [X] Bypass capacitors are less than 1cm away from their respective IC's power pins.

### 3D Spacing
- [X] Layout of components have been placed with mounting location and usage of the board in mind.
    - Are PCBs going to be stacked on above/below this board? Are tall components placed accordingly?
    - Are buttons and lights easily accessible and viewable?
    - When mounted into the car, are the heights of the components and connectors accounted for?
- [ ] I am not reading every word and I need to start this checklist over.
    - Please uncheck everything you have checked and start over.
- [x] Location of connectors and wires going out of the board will prevent messy wiring.
    - Are all the wires that are going in the same direction placed on the same edge of the board?

### Components
- [X] Do footprints match the schematic?
    - Make sure pins on the footprint correspond to pins in the schematic 
    - (e.g. counterclockwise pins on footprint and alternating pins on schematic is *bad*)
- [X] Custom footprints have been double checked with the datasheet.
- [X] Footprints are consistent across the PCB: *i.e. all 0805 for Resistors/Capacitors*
- [x] Pin 1 of the footprint is labeled in some way. 
- [X] Are LED's in easy to see places? 
- [X] Are test points in easy to reach places?  
- [X] Are critical paths of switching converters as small as possible?  

### Copper Layer 
- [X] The trace widths and trace clearances are greater than JLCPCB's minimum requirements (https://jlcpcb.com/capabilities/Capabilities). 
    - [x] Are signal traces are .15mm unless provided with reasoning?   
        - NOTE: One net can have multiple trace widths  
- [X] The trace lengths are as short as possible. 
    - Can there be a more optimal route if you go to another layer? 
- [x] Each trace's width is capable of handling the expected current flow. 
    - Use PCB width calculator to calculate trace width. 
- [X] *No sharp corners. No trace angles equal to or less than 90 degrees. 
    - Orthogonal traces should have vias if necessary. 
- [ ] Are edges of board surrounded by clean ground on both layers with stitching vias?  
- [x] Traces are in parallel with each other when possible (exceptions can be made to prevent signal coupling). 
    - E.g. traces connected between an IC and MCU can be placed in parallel with each other. 
- [X] There are no random trace appendages. 
- [X] Vias placed in copper pads are fully encompassed in the copper pads. 
- [X] Through-hole components do not have extraneous vias. 
- [x] Vias should be appropriately sized according to the connected net(s) and expected current capacity.

*Not really a problem for modern manufacturing techniques but good practice and important for high speed signal integrity.

### Silkscreen Layer
- [X] Visible text sizes are greater than .8mm(L), .8mm(H), .15mm(W).
- [X] All visible text is on the silkscreen layer.
- [X] All reference labels of each component are not overlapping a copper pad or another component.
- [x] All connector pins are labeled with a meaningful and helpful name.
- [x] All LEDs are labeled with a meaningful and helpful name.
- [X] Silkscreens are mostly facing one direction (or 2). 

### Edge Cut Layer
- [x] The dimensions of the board and the mounting holes are nice values in metric i.e. no long decimals.
- [X] The physical outline of the board is on the edge cut layer.
- [X] Edge cuts are straight and parallel with opposite edge of the board.
- [x] Mounting holes are aligned and support M3 screws. All mounting holes should have distances between them shown in comments layer.
- [x] Corners are curved and contoured to mounting holes.

**Please *read* every word on *every* bullet point before checking off the corresponding box.**

## IMPORTANT NOTICE
- [x] I am confident that this board will be safe to use in a safety critical environment.
- [x] I have read every word on every bullet point and have only checked off a bullet point if I have read every word.
- [x] ((( **OPTIONAL** ))) I had fun :^)

## Other Comments
_Write any comments about the board that would help the reviewers here._

### CODE REVIEW

**Comment by FrankLiTX** [comment]
image
try reduce the number of these trace "turns"

- if you could try place all of the test points in one location (top of the board perhaps)

image
- not sure if the humidity sensor has a direction, but if not, rotating this 90 degrees could simplify the traces a bit

- run ERC on your sch. There are some issues with your power delivery (e.g. 12V not connected to an input source).

**Comment by FrankLiTX** [comment]
- have a look at your 12 V and GND planes while the other is hidden. 12V specifically is cut up a lot and can only travel through some select areas. Not your fault since it is unfortunately really difficult to not cut it up given how the PSOM connector and CAN in and out are on the other side of each other. One thing i would suggest is using back layer traces for the CAN h and l since theres nothing at the bottom of the board that needs to connect to GND.
- ive also noticed that in some areas, there are unnecessary vias as a result of conflicting traces. A good rule of thumb to address them would be to have the front and back traces follow a strict direction. e.g. front traces go in the top / bottom direction, and back traces go in the left / right, or vice versa.
- for your humidity sensor, try place your other passive components as close as possible.

**Comment by Lakshay983** [comment]
Looks really good! I like the consistency in the direction of your traces. 

Make sure to run DRC on the board since a few errors popped up. Two of the warnings you're getting are that the via is only connected onone side. For example, this 12V_In trace is on the top layer and it is going to a top layer plane so you don't need a via. You need a via for GNDPWR since GNDPWR is on the bottom layer and you are doing a via to it.
image

You're getting thermal relief errors, basically in a plane you need a few connections to a pad for it to pass JLCPCB's design rules. Here you only have one, but a minimum of two are required. When I have this error I like to see what is preventing the plane from filling into the other sides of the pad. In this case it's both the GND via and the PA1 trace. Moving the GND via down a little bit fills it one side. You can also do some shenanigans with the PA1 trace by moving it to the other side. 
image

Looking at the 3D model, I don't really like that the connectors are on the bottom but I see it's cuz u wanted to make the board small. Did you make sure to talk to Frank and Emech about this? Did you also check with emech if this board needs its own mounting hole. Also, I'd add a testpoint for the analog output of the temp sensor.
image

I question the need for a big power plane for 12V and GNDPWR. If the benefit is a higher current then that higher current is getting choked by that smaller trace soooooo. There's a benefit of capacitance on the plane, but I'd just add more capacitors. You can make the 12V and GNDPWR traces into fills that are localized to just connect what you need (weird fucky rectangles).

**Comment by Lakshay983** [comment]
Also, what was the consensus on this board in regards to water proofing and enclosures? For the airflow and temperature specifically

**Comment by Rav4s** [comment]
These mounting holes should be fine according to emech. They also said waterproofing isn't necessary so we should be good with the sensors. I'll work on fixing the rest, thank you!

**Comment by Lakshay983** [comment]
image
Would personally prefer to have testpoints on the front
Same for the LED
Since you have so much space on the back of the board, it'd be cool to keep most components to one side of the board (just for ease of soldering). Stuff like LEDs and testpoints still keep on the front.
Protip: you can the B.Fab and F.Fab layers to make ur eyes not in pain
The temp chip routing is a lil bit messy (honestly not that deep tho). Prioritizing easy of the VDDA and GNDA pins makes things a bit cleaner. Have the bypass cap parallel horizontally also helps so you can keep all your VDDA traces in one little section. Up to you tho, it's pretty small.
image

image
In general, it's nice to keep components pointing in the same direction just for ease of soldering and since you have the space you can make the traces a lil bit more wonky. so stuff like flipping the vreg cap.
image
For ease of debugging, can you add some headers for a logic analyzer (just the 2.54 pitch breadboard ones) to your I2C sensors. It'll make whoever is writing a drivers lives easier.

since it doesn't look like it's filling inside the connector, you can route stuff like the PA1(ADC) inside the connector footprint and make that red to keep trace consistency.



image

**Comment by ppatra126** [comment]
i agree w lakshays points about test points and less. even if you have to extend the board a bit i would probably try and make them accessible from the top. shouldn't really matter but i would probably route the CAN_L trace underneath the connector so you don't really choke ground power at the bottom but again shouldn't really matter since things are such low current anyways.
image

**Comment by Rav4s** [comment]
merging to move to purely breakout implementation

**Pull request merged**
